"""Initial migration: users and auth_tokens

Revision ID: 432576a07748
Revises: 701ea1d79e33
Create Date: 2025-12-02 23:21:03.486299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432576a07748'
down_revision = '701ea1d79e33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camaras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'OCUPADA', 'MANUTENCAO', name='statuscamara'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camaras_id'), 'camaras', ['id'], unique=False)
    op.create_index(op.f('ix_camaras_nome'), 'camaras', ['nome'], unique=True)
    op.create_index(op.f('ix_camaras_status'), 'camaras', ['status'], unique=False)
    op.create_table('cargas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_chegada', sa.DateTime(), nullable=False),
    sa.Column('fornecedor', sa.String(length=255), nullable=False),
    sa.Column('fazenda', sa.String(length=255), nullable=True),
    sa.Column('tipo_banana', sa.Enum('NANICA', 'PRATA', 'MACA', 'OUTRA', name='tipobanana'), nullable=False),
    sa.Column('qualidade_inicial', sa.String(length=50), nullable=True),
    sa.Column('quantidade_caixas', sa.Integer(), nullable=False),
    sa.Column('preco_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('EM_ESTOQUE', 'ENCERRADA', name='statuscarga'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargas_id'), 'cargas', ['id'], unique=False)
    op.create_index(op.f('ix_cargas_status'), 'cargas', ['status'], unique=False)
    op.create_index(op.f('ix_cargas_tipo_banana'), 'cargas', ['tipo_banana'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('CEASA', 'MERCADO', 'ATACADO', 'SACOLAO', 'OUTRO', name='tipocliente'), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_ativo'), 'clientes', ['ativo'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_index(op.f('ix_clientes_tipo'), 'clientes', ['tipo'], unique=False)
    op.create_table('gastos_internos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.Enum('VALE_TRANSPORTE', 'GASOLINA', 'ADMINISTRATIVO', 'MANUTENCAO', 'OUTRO', name='tipogasto'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_internos_data'), 'gastos_internos', ['data'], unique=False)
    op.create_index(op.f('ix_gastos_internos_id'), 'gastos_internos', ['id'], unique=False)
    op.create_index(op.f('ix_gastos_internos_tipo'), 'gastos_internos', ['tipo'], unique=False)
    op.create_table('rotas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('motorista', sa.String(length=255), nullable=True),
    sa.Column('veiculo', sa.String(length=100), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PLANEJADA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='statusrota'), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rotas_data'), 'rotas', ['data'], unique=False)
    op.create_index(op.f('ix_rotas_id'), 'rotas', ['id'], unique=False)
    op.create_index(op.f('ix_rotas_status'), 'rotas', ['status'], unique=False)
    op.create_table('logs_operacionais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('LOGIN', 'PESAGEM', 'CARREGAMENTO', 'ATUALIZACAO', 'DEVOLUCAO', 'MOVIMENTACAO', 'OUTRO', name='tipolog'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('referencia_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_operacionais_data'), 'logs_operacionais', ['data'], unique=False)
    op.create_index(op.f('ix_logs_operacionais_id'), 'logs_operacionais', ['id'], unique=False)
    op.create_index(op.f('ix_logs_operacionais_referencia_id'), 'logs_operacionais', ['referencia_id'], unique=False)
    op.create_index(op.f('ix_logs_operacionais_tipo'), 'logs_operacionais', ['tipo'], unique=False)
    op.create_index(op.f('ix_logs_operacionais_usuario_id'), 'logs_operacionais', ['usuario_id'], unique=False)
    op.create_table('movimentacoes_camara',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camara_id', sa.UUID(), nullable=False),
    sa.Column('carga_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('tipo_movimento', sa.Enum('ENTRADA', 'SAIDA', name='tipomovimento'), nullable=False),
    sa.Column('quantidade_caixas', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camara_id'], ['camaras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_camara_camara_id'), 'movimentacoes_camara', ['camara_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_camara_carga_id'), 'movimentacoes_camara', ['carga_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_camara_data'), 'movimentacoes_camara', ['data'], unique=False)
    op.create_index(op.f('ix_movimentacoes_camara_id'), 'movimentacoes_camara', ['id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_camara_tipo_movimento'), 'movimentacoes_camara', ['tipo_movimento'], unique=False)
    op.create_table('ocr_inputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('imagem_url', sa.String(length=500), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('confianca', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_inputs_cliente_id'), 'ocr_inputs', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ocr_inputs_data'), 'ocr_inputs', ['data'], unique=False)
    op.create_index(op.f('ix_ocr_inputs_id'), 'ocr_inputs', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('origem_pedido', sa.Enum('MANUAL', 'OCR', 'WHATSAPP', 'TELEFONE', 'OUTRO', name='origempedido'), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'SEPARADO', 'ENVIADO', 'DEVOLUCAO', 'ENCERRADO', name='statuspedido'), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_cliente_id'), 'pedidos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pedidos_data'), 'pedidos', ['data'], unique=False)
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_origem_pedido'), 'pedidos', ['origem_pedido'], unique=False)
    op.create_index(op.f('ix_pedidos_status'), 'pedidos', ['status'], unique=False)
    op.create_table('perdas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carga_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('quantidade_caixas', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('valor_estimado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perdas_carga_id'), 'perdas', ['carga_id'], unique=False)
    op.create_index(op.f('ix_perdas_data'), 'perdas', ['data'], unique=False)
    op.create_index(op.f('ix_perdas_id'), 'perdas', ['id'], unique=False)
    op.create_table('pesagens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('carga_id', sa.UUID(), nullable=False),
    sa.Column('quantidade_caixas', sa.Integer(), nullable=False),
    sa.Column('peso_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('operador_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'CARREGADO', 'ENVIADO', name='statuspesagem'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operador_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesagens_carga_id'), 'pesagens', ['carga_id'], unique=False)
    op.create_index(op.f('ix_pesagens_cliente_id'), 'pesagens', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pesagens_data'), 'pesagens', ['data'], unique=False)
    op.create_index(op.f('ix_pesagens_id'), 'pesagens', ['id'], unique=False)
    op.create_index(op.f('ix_pesagens_operador_id'), 'pesagens', ['operador_id'], unique=False)
    op.create_index(op.f('ix_pesagens_status'), 'pesagens', ['status'], unique=False)
    op.create_table('devolucoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('quantidade_caixas', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('valor_estornado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devolucoes_cliente_id'), 'devolucoes', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_devolucoes_data'), 'devolucoes', ['data'], unique=False)
    op.create_index(op.f('ix_devolucoes_id'), 'devolucoes', ['id'], unique=False)
    op.create_index(op.f('ix_devolucoes_pedido_id'), 'devolucoes', ['pedido_id'], unique=False)
    op.create_table('entregas_cliente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rota_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=True),
    sa.Column('quantidade_caixas', sa.Integer(), nullable=False),
    sa.Column('devolucao', sa.Boolean(), nullable=False),
    sa.Column('horario', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rota_id'], ['rotas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entregas_cliente_cliente_id'), 'entregas_cliente', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_entregas_cliente_id'), 'entregas_cliente', ['id'], unique=False)
    op.create_index(op.f('ix_entregas_cliente_pedido_id'), 'entregas_cliente', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_entregas_cliente_rota_id'), 'entregas_cliente', ['rota_id'], unique=False)
    op.create_table('itens_pedido',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('tipo_banana', sa.Enum('NANICA', 'PRATA', 'MACA', 'OUTRA', name='tipobanana'), nullable=False),
    sa.Column('quantidade_caixas', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_pedido_id'), 'itens_pedido', ['id'], unique=False)
    op.create_index(op.f('ix_itens_pedido_pedido_id'), 'itens_pedido', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_itens_pedido_tipo_banana'), 'itens_pedido', ['tipo_banana'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_pedido_tipo_banana'), table_name='itens_pedido')
    op.drop_index(op.f('ix_itens_pedido_pedido_id'), table_name='itens_pedido')
    op.drop_index(op.f('ix_itens_pedido_id'), table_name='itens_pedido')
    op.drop_table('itens_pedido')
    op.drop_index(op.f('ix_entregas_cliente_rota_id'), table_name='entregas_cliente')
    op.drop_index(op.f('ix_entregas_cliente_pedido_id'), table_name='entregas_cliente')
    op.drop_index(op.f('ix_entregas_cliente_id'), table_name='entregas_cliente')
    op.drop_index(op.f('ix_entregas_cliente_cliente_id'), table_name='entregas_cliente')
    op.drop_table('entregas_cliente')
    op.drop_index(op.f('ix_devolucoes_pedido_id'), table_name='devolucoes')
    op.drop_index(op.f('ix_devolucoes_id'), table_name='devolucoes')
    op.drop_index(op.f('ix_devolucoes_data'), table_name='devolucoes')
    op.drop_index(op.f('ix_devolucoes_cliente_id'), table_name='devolucoes')
    op.drop_table('devolucoes')
    op.drop_index(op.f('ix_pesagens_status'), table_name='pesagens')
    op.drop_index(op.f('ix_pesagens_operador_id'), table_name='pesagens')
    op.drop_index(op.f('ix_pesagens_id'), table_name='pesagens')
    op.drop_index(op.f('ix_pesagens_data'), table_name='pesagens')
    op.drop_index(op.f('ix_pesagens_cliente_id'), table_name='pesagens')
    op.drop_index(op.f('ix_pesagens_carga_id'), table_name='pesagens')
    op.drop_table('pesagens')
    op.drop_index(op.f('ix_perdas_id'), table_name='perdas')
    op.drop_index(op.f('ix_perdas_data'), table_name='perdas')
    op.drop_index(op.f('ix_perdas_carga_id'), table_name='perdas')
    op.drop_table('perdas')
    op.drop_index(op.f('ix_pedidos_status'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_origem_pedido'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_data'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_cliente_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_ocr_inputs_id'), table_name='ocr_inputs')
    op.drop_index(op.f('ix_ocr_inputs_data'), table_name='ocr_inputs')
    op.drop_index(op.f('ix_ocr_inputs_cliente_id'), table_name='ocr_inputs')
    op.drop_table('ocr_inputs')
    op.drop_index(op.f('ix_movimentacoes_camara_tipo_movimento'), table_name='movimentacoes_camara')
    op.drop_index(op.f('ix_movimentacoes_camara_id'), table_name='movimentacoes_camara')
    op.drop_index(op.f('ix_movimentacoes_camara_data'), table_name='movimentacoes_camara')
    op.drop_index(op.f('ix_movimentacoes_camara_carga_id'), table_name='movimentacoes_camara')
    op.drop_index(op.f('ix_movimentacoes_camara_camara_id'), table_name='movimentacoes_camara')
    op.drop_table('movimentacoes_camara')
    op.drop_index(op.f('ix_logs_operacionais_usuario_id'), table_name='logs_operacionais')
    op.drop_index(op.f('ix_logs_operacionais_tipo'), table_name='logs_operacionais')
    op.drop_index(op.f('ix_logs_operacionais_referencia_id'), table_name='logs_operacionais')
    op.drop_index(op.f('ix_logs_operacionais_id'), table_name='logs_operacionais')
    op.drop_index(op.f('ix_logs_operacionais_data'), table_name='logs_operacionais')
    op.drop_table('logs_operacionais')
    op.drop_index(op.f('ix_rotas_status'), table_name='rotas')
    op.drop_index(op.f('ix_rotas_id'), table_name='rotas')
    op.drop_index(op.f('ix_rotas_data'), table_name='rotas')
    op.drop_table('rotas')
    op.drop_index(op.f('ix_gastos_internos_tipo'), table_name='gastos_internos')
    op.drop_index(op.f('ix_gastos_internos_id'), table_name='gastos_internos')
    op.drop_index(op.f('ix_gastos_internos_data'), table_name='gastos_internos')
    op.drop_table('gastos_internos')
    op.drop_index(op.f('ix_clientes_tipo'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_ativo'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_cargas_tipo_banana'), table_name='cargas')
    op.drop_index(op.f('ix_cargas_status'), table_name='cargas')
    op.drop_index(op.f('ix_cargas_id'), table_name='cargas')
    op.drop_table('cargas')
    op.drop_index(op.f('ix_camaras_status'), table_name='camaras')
    op.drop_index(op.f('ix_camaras_nome'), table_name='camaras')
    op.drop_index(op.f('ix_camaras_id'), table_name='camaras')
    op.drop_table('camaras')
    # ### end Alembic commands ###

